apiVersion: v1
kind: Service
metadata:
  name: upd-app
  labels:
    {{- include "upd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "upd.selectorLabels" . | nindent 4 }}