# Generated by Django 3.1.3 on 2020-11-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0002_auto_20201109_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='last_pulled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
