# Generated by Django 3.1.3 on 2020-11-09 20:23

from django.db import migrations, models
import upd.models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0003_auto_20201109_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='fw',
            field=models.FileField(default=1, upload_to=upd.models.fw_upload_to),
            preserve_default=False,
        ),
    ]
