# Generated by Django 3.1.3 on 2020-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0005_auto_20201110_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-indexed']},
        ),
        migrations.AddField(
            model_name='version',
            name='pullable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='plugin',
            field=models.CharField(choices=[('plugins.ubiquiti.base.UbiquitiFirmwarePlugin', 'Ubiquiti Firmware Plugin'), ('plugins.grandstream.base.GrandstreamFirmwarePlugin', 'Grandstream Firmware Plugin'), ('plugins.zyxel.base.ZyxelFirmwarePlugin', 'ZyXEL Firmware Plugin')], max_length=255),
        ),
    ]
