# Generated by Django 3.1.3 on 2020-11-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0006_auto_20201110_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
