# Generated by Django 3.1.3 on 2020-11-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='date_indexed',
            new_name='indexed',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='date_pulled',
            new_name='last_pulled',
        ),
    ]
